#!/usr/bin/env bash
DEFAULT_NOTIFY="harrythedevopsguy@gmail.com"
DOMAINS=()
DOMAIN_LIST=(
      'https://docs.google.com/spreadsheets/d/e/2PACX-1vScqQ8BfTdgZ8WqGL9e7953dGhr61fDiNlTRs99bqtWRwSuXyDXe8uDnRsYvPddHaPA49cor1eu20bW/pub?gid=0&single=true&output=csv'
      'https://docs.google.com/spreadsheets/d/e/2PACX-1vTuqhESSxtJv79LWRPju3m_mkdhZFQaQi753p51HAQX5nzi65gCu-AbZkQDeEZGm4GE4Wmeoj6X2lFt/pub?gid=0&single=true&output=csv'
  )

for GSHEET in ${DOMAIN_LIST[@]}; do
  IFS=","
   curl -sL  "${GSHEET}" |awk -F',' '{print $1"," $2}'|sed '1d'|while read domain email_id xdays remarks
  do
    if [[ -z "${email_id}" ]]; then
        DOMAINS+=(${domain})
        export TRIGGER='true'
      else
        mcert -d "$domain" -s "#devops" -e "${email_id}" -x ${xdays:-30} -V
    fi
  done
  if [[ "${TRIGGER}" == 'true' ]]; then
    echo "checking again." "$(echo ${DOMAINS[@]})"
    mcert -d "$(echo ${DOMAINS[@]})" -s "#devops" -e "${DEFAULT_NOTIFY}" -x ${xdays:-30} -V
  fi
done
