# This is a basic workflow to help you get started with Actions

name: Run mCert-manager

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * *'

  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ dev ]
#   pull_request:
#     branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        google_sheet:
          - 'https://docs.google.com/spreadsheets/d/e/2PACX-1vScqQ8BfTdgZ8WqGL9e7953dGhr61fDiNlTRs99bqtWRwSuXyDXe8uDnRsYvPddHaPA49cor1eu20bW/pub?gid=0&single=true&output=csv'
          - 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTuqhESSxtJv79LWRPju3m_mkdhZFQaQi753p51HAQX5nzi65gCu-AbZkQDeEZGm4GE4Wmeoj6X2lFt/pub?gid=0&single=true&output=csv'


    container:
      image: harry97/mcloud-toolkit:latest
      env:
        SLACK_CLI_TOKEN: ${{ secrets.DEFAULT_SLACK_TOKEN }}
        SENDGRID_API_KEY: ${{ secrets.DEFAULT_SENDGRID_TOKEN }}
        EMAIL_FROM: mcloudautomation@gmail.com
        EMAIL_MODE: SENDGRID
        REPLY_EMAIL_ADDRESS: 'Harry <HarryTheDevOpsGuy@gmail.com>'



    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world! ${{ matrix.google_sheet }}
        with:
          gsheet: ${{ matrix.google_sheet }}
      # Runs a single command using the runners shell
      #- name: Check Cert expiry
      #  run: mcert -d google.com -x 80 -s '#devops' -e harrythedevopsguy@gmail.com

      # Check SSL certs
      - name: Check Cert expiry
        run: ./scripts/mcert-manager

      # Runs a single command using the runners shell
      #- name: Send Email Using mSend
      #  run: msend -t harrythedevopsguy@gmail.com -s 'github workflow subject' -m 'github workflow'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo slack - $SLACK_CLI_TOKEN
          pwd
          echo $HOME
          echo Add other actions to build,
          echo test, and deploy your project.
          ls -la
          env
